fj_hw_4
g1S0/kotlintask pull request #1
Opened 2024-09-17 20:26 UTC by g1S0

2024-09-21 15:22 UTC, SHvatov requested changes
@g1S0 оставил пару минорных комментариев, а так 🔥 Как тебе вообще котлин? Такое чувство, что ты с ним уже работал))

2024-09-21 15:22 UTC, SHvatov commented on src/main/kotlin/Main.kt
> +            header(2) { news.title }
🔥

2024-09-21 15:22 UTC, SHvatov commented on src/main/kotlin/Main.kt
> +    println("Fetching $count news...")
Давай на логгирование заменим, раз оно уже подключено

2024-09-21 15:22 UTC, SHvatov commented on src/main/kotlin/Main.kt
> +        println("Error saving news!")
Аналогично, + не стоит скрывать оригинальное исключение, его лучше куда-нибудь вывести, чтобы знать, что пошло не так.

2024-09-21 15:22 UTC, SHvatov commented on src/main/kotlin/dsl/NewsPrinter.kt
> +class NewsPrinter {
👍

2024-09-21 15:22 UTC, SHvatov commented on src/main/kotlin/serivce/impl/FileSaveServiceImpl.kt
> +        if (file.exists()) {
Немного неочевидный АПИ метода получается) Я бы подумал, что раз ожидается на вход файл, то моя задача его создать и провалидировать. Тут либо ты просишь путь, и сам занимаешься созданием, либо просишь на вход файл, и перекладываешь ответственность на вызывающего) Предлагаю все-таки первый вариант)

2024-09-21 15:22 UTC, SHvatov commented on src/main/kotlin/serivce/impl/FileSaveServiceImpl.kt
> +                writer.newLine()
О, не советую, ибо у того, кто будет парсить файл, будет много вопросов))

2024-09-24 14:09 UTC, g1S0 commented on src/main/kotlin/serivce/impl/FileSaveServiceImpl.kt
> +        if (file.exists()) {
Окей, тогда придется подумать как переписать тест, потому что сейчас я таким методом создаю мок в тесте.

2024-09-24 14:10 UTC, g1S0 commented on src/main/kotlin/serivce/impl/FileSaveServiceImpl.kt
> +                writer.newLine()
Не очень понял что здесь надо переделать

2024-09-24 20:00 UTC, SHvatov commented on src/main/kotlin/serivce/impl/FileSaveServiceImpl.kt
> +        if (file.exists()) {
Можно в тестовых ресурсах генерить файлики

2024-09-24 20:01 UTC, SHvatov commented on src/main/kotlin/serivce/impl/FileSaveServiceImpl.kt
> +                writer.newLine()
Я про пустую строку в CSV-файле. При парсинге такого никогда не ожидаешь, и очень обидно словить ошибку парсинга / валидации, потому что сразу после заголовка - пустая строка.

2024-09-25 19:46 UTC, g1S0 commented
поправил

2024-10-04 12:27 UTC, SHvatov approved these changes
@g1S0 🚀

2024-10-04 22:57 UTC, merged